name: pfa_projet
description: "A new Flutter project."

publish_to: 'none' # This determines if the project is published to pub.dev (none = private).

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_ml_kit: ^0.19.0
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  http: ^1.2.2
  flutter_secure_storage: ^9.2.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
